### ISSUE TITLE
Bug with duke fishron in pve

### ISSUE THREAD

**Issue by BMXLinkmaster** [popstarfreas/DG-TS#102]
I have no idea what caused it, but it was weird.
I was fighting dukes in the arena like normal, but then they started spawning with crawltipedes 
I've never seen anything like it before, and i have no idea if it was local / client side, or global / server side.

![Terraria 2021 01 19 - 19 28 09 01_Moment](https://user-images.githubusercontent.com/77711173/105124261-a11fbe00-5a8e-11eb-8892-f85eca4fa5c9.jpg)
![Terraria 2021 01 19 - 19 28 09 01_Moment(2)](https://user-images.githubusercontent.com/77711173/105124273-ada41680-5a8e-11eb-8eb6-9ff46aa56906.jpg)
![Terraria 2021 01 19 - 19 28 09 01_Moment(3)](https://user-images.githubusercontent.com/77711173/105124294-b694e800-5a8e-11eb-83c8-c4cb05013e74.jpg)
![Terraria 2021 01 19 - 19 28 09 01_Moment(4)](https://user-images.githubusercontent.com/77711173/105124315-c01e5000-5a8e-11eb-95fd-1ddde0d81554.jpg)
![Terraria 2021 01 19 - 19 28 09 01_Moment(5)](https://user-images.githubusercontent.com/77711173/105124339-c8768b00-5a8e-11eb-8c12-2e3d8793029a.jpg)

**Comment by Arthri** [comment]
I couldn't get it on cam but i've experienced a similar bug before, were you fighting crawtipedes shortly before?

**Comment by popstarfreas** [comment]
https://forum.dark-gaming.com/c/bug-reports/32
