### ISSUE TITLE
Spectating in Duels

### ISSUE THREAD

**Issue by GoldenRound** [popstarfreas/DG-TS#11]
With duels in pvp being reopened (or soon to be reopened, if they aren't already) 
Some people like to spectate them, I'm stupid and know nothing about programming, but a join command of /spectate and /warp to the arena could maybe be done, I think being able to spectate a duel would be incredibly cool to do, especially when you are able to use hooks in spectate mode.

**Comment by Fraxo** [comment]
I very much agree, spectating duels is very interesting for learning, and burning time when not feeling up to do much else, so presuming this is possible, which I don't see why it couldn't be, I strongly support this

**Comment by Fraxo** [comment]
Spectating in duels is now functional, however, it is very inconsistent.
Often times if you exit spectating a duel and try to spectate again you will not be able to, or the cooldown will set itself to something like a few hours, forcing you to leave and rejoin a few times until it fixes itself. 
I will edit this post with more finite details about how it breaks in the near future.
