### ISSUE TITLE
/house help listing invalid subcommands

### ISSUE THREAD

**Issue by popstarfreas** [popstarfreas/DG-TS#34]
/house chat and /house vistor are listed in housing commands help page 4 but do not work as subcommands

**Comment by Marcus101RR** [comment]
**Patch Notes**
- [**HousingDistricts**] Issue #34 has been fixed (removed chat/visitor) from subcommands. [V. 2.5.2]

Awaiting an Administrator to apply new plugin update to the server (located on Leafos Desktop session under updates).

**Comment by popstarfreas** [comment]
Update will be applied on next Survival restart (when everything resets).
