### ISSUE TITLE
Brain Sucklers go invisible when the victim dies

### ISSUE THREAD

**Issue by popstarfreas** [popstarfreas/DG-TS#38]
Brain Sucklers will go invisible when the victim it is latched onto dies, causing the round to be impossible to complete.

Current workaround: use "/ability telekinesis" to force server mob update to make it visible again

**Comment by KceGio** [comment]
Brain Sucklers are teleported into the lobby where they make the player continuously die since the brain suckler is invincible while in the lobby, there is also a chance to escape when it gives up, or to latch on another person

**Comment by popstarfreas** [comment]
NPCs get cleared when they are too far out of the zombie map.
