### ISSUE TITLE
This can be closed

### ISSUE THREAD

**Issue by Fraxo** [popstarfreas/DG-TS#48]
Rofle prefers separate issues be made for small things, so this can be deleted / closed

**Comment by KceGio** [comment]
* Give Crew free /buildmode perms
* Encase Dimension Name in braces :
`{Rift} [Admin] <Blanc> : Vote for DG`
* Purge Crimson/Hallow/Corruption from build

**Comment by KceGio** [comment]
you can close this yourself, you know that right?.. its beside the comment button
