### ISSUE TITLE
Staff Title Display over Dimensions

### ISSUE THREAD

**Issue by Fraxo** [popstarfreas/DG-TS#52]
Have Staff / Dimension Manager titles appear next to dimension name ie: 
[Rift] [Admin] Lord Avery : DG is so cool

**Comment by popstarfreas** [comment]
I think the plan is to format it like:
Dimension> [Title] <User name> (Tag) : Message

see zombies lobby chat.

**Comment by popstarfreas** [comment]
Above is now the current format.
