### ISSUE TITLE
public lobby chat and .silentcommands

### ISSUE THREAD

**Issue by Quinci135** [popstarfreas/DG-TS#76]
Silent commands with a fullstop "." can be done after toggling lobby chat to public.
This bypasses some command restrictions,  unintentionally allowing use of some commands:
- .item
- .loadout
- .tp
- .warp
- .home
- .spawn

**Comment by popstarfreas** [comment]
Someone confirm if this is now fixed.

**Comment by Quinci135** [comment]
Command limitations for "/" now cannot be bypassed with ".'
