### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by al5ina5** [popstarfreas/DG-TS#79]
Hey there,

First of all, sorry if this isn’t the correct place for this.

I found your username on the TShock forums and follow the username to find you here. I was wondering you offered some support for plugin development? I have a few questions I believe are very simple to a skilled programmer like you. Do you have a Discord or Telegram in which I can contact you?

Thanks a lot, and once again, sorry for the bother if you don’t offer this type of support.

**Comment by popstarfreas** [comment]
You can join Dark Gaming's discord via https://discordapp.com/invite/aRmJvH
I am popstarfreas#3902 on Discord.
