### ISSUE TITLE
(DTP) Remove all titles and tags what correlate with negativity 

### ISSUE THREAD

**Issue by KceGio** [popstarfreas/DG-TS#85]
**Is your feature request related to a problem? Please describe.**
There are a few titles and tags on DTP right now that go along the lines of "The Hated" "Weirdo" "Beggar" "Failure" "Idiot" "The Loner" "The Shattered"

![DTP Shop](https://media.discordapp.net/attachments/459819294730092557/671345162298851347/unknown.png)

**Describe the solution you'd like**
These titles and tags should be removed, in order to prevent people from complaining about losing their tags and titles, it could be replaced with a time, or another title and tag of equal rarity

**Comment by popstarfreas** [comment]
It's not clear what you are asking. Are you saying no titles/tags should contain potentially negative words or that the shop shouldn't sell them?

**Comment by KceGio** [comment]
I'm asking them to be removed

**Comment by popstarfreas** [comment]
It's not clear what the benefit is. You need to explain more about why they should be removed, how that would benefit the system and what their replacements would be.

**Comment by KceGio** [comment]
Some people like I, don't really like those items, an alternative solution might be being able to swap an item for another item of equal rarity for a small fee, DP or Creds, lifetime of the item might also work

**Comment by popstarfreas** [comment]
But you can currently use them to restore other items lifetime. You either buy in the shop a good title/tag or you get one from a lootbox. Then you can restore your good item(s) using the ones you don't like/don't want.  Also given that they're low rarity, you'll be getting loads of them anyway, so you may even eventually get one that you want. Why do you also need to be able to swap them?

**Comment by KceGio** [comment]
Nevermind
