### ISSUE TITLE
/i Sandstone Wall 999

### ISSUE THREAD

**Issue by Christoffer92** [popstarfreas/DG-TS#87]
Hi,

I joined as a guest on the server "t.dark-gaming.com" to obtain the unobtainable item: sandstone wall.
But sadly when you typed "/i sandstone wall 999" into the chat
A green text comes up as if you would have gotten them but there are not to be seen in your invetory.

So if Sandstone wall and Hardened Sand Walls could be obtained that could be awesome.

best regards, Christoffer.

**Comment by KceGio** [comment]
The item itself is unobtainable. It despawns the moment it enters your inventory, just like fragment hammers/axes, this also applies to it's Crimson/Corruption/Hallow variants.

**Comment by Christoffer92** [comment]
Oh okay, i see.. Well thanks for the reply and information
