### ISSUE TITLE
Zombies game breaking sentry bug (round 2 max) 

### ISSUE THREAD

**Issue by 1Christoff** [popstarfreas/DG-TS#93]
This bug is a two player bug and takes two games for it to work. In the first game, you get to a decent round, maybe round 10+. When you lose, one person leaves from the lobby, while another has /ability sentry already activated. This glitches out the system and gives you money in the intermission zone. This combines with another bug that lets you place a sentry in the intermission zone. (placing a sentry when it says "spawning in 5.. 4.. 3.." in chat). Combining these two you can place a bank and spam upgrades on it in the intermission zone. Once you spawn, you invite that player back and let yourself die. When you die, pick up the sentry that is in the intermission area (the one you upgraded). Now you can perform the refund bug with banks. You place the upgraded bank in a place where zombies will destroy it, before that bank gets destroyed, you place another bank to get the money from it. If this is successful, you can have 100m on round two, depending on the amount of upgrades you put into the sentry.

I managed to max on the map "Skelotens" on round 2, which is op because it has Solar Eruption and Lunar Flare.

**Comment by popstarfreas** [comment]
I made some changes. Can you check this again and tell me whether this is still possible?

**Comment by 1Christoff** [comment]
everything seems good! you cant place any more sentries inside the intermission, so this bug no longer works
