### ISSUE TITLE
Lost Account

### ISSUE THREAD

**Issue by MLGDoge123** [popstarfreas/DG-TS#97]
MLGDoge123 here,  I wanted to check my DP on https://dark-gaming.com/ to finally buy crew. I was all of a sudden logged off and i cant log in.
My account name:MLGDoge123 or MLGDOGE123

**Comment by popstarfreas** [comment]
What do you mean by "cant log in"?

**Comment by popstarfreas** [comment]
Also as this is a support issue I recommend either our discord's #help-and-support or https://forum.dark-gaming.com/c/help-support/10
